// <auto-generated />
using System;
using IntegradorIdeas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntegradorIdeas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427001122_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntegradorIdeas.Models.Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCreative")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWellFormulated")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfessorObservation")
                        .HasColumnType("text");

                    b.Property<int?>("SimilarToIdeaId")
                        .HasColumnType("integer");

                    b.Property<double?>("SimilarityPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SimilarToIdeaId");

                    b.HasIndex("TeamId");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("IntegradorIdeas.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Member1Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Member2Name")
                        .HasColumnType("text");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("IntegradorIdeas.Models.Idea", b =>
                {
                    b.HasOne("IntegradorIdeas.Models.Idea", "SimilarToIdea")
                        .WithMany()
                        .HasForeignKey("SimilarToIdeaId");

                    b.HasOne("IntegradorIdeas.Models.Team", "Team")
                        .WithMany("Ideas")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimilarToIdea");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("IntegradorIdeas.Models.Team", b =>
                {
                    b.Navigation("Ideas");
                });
#pragma warning restore 612, 618
        }
    }
}
